name: Release

on: [workflow_call]

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Delete previous nightly release
        run: |
            gh release --repo ${{ github.repository }} delete nightly --cleanup-tag
        env:
          GH_TOKEN: ${{ github.token }}
        continue-on-error: true  # In case the release doesn't exist yet
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          path: src
          fetch-depth: 0
      - name: Create nightly tag
        run: |
            git -C src tag nightly
            git -C src push origin nightly
      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          path: bin
      - name: Release info
        id: release_info
        run: |
            echo "now=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
            echo "message=$(git -C src log -1 --pretty=%s)" >> $GITHUB_OUTPUT
            echo 'files<<EOF' >> $GITHUB_OUTPUT
            find bin -name '*.tar.gz' -o -name '*.zip' >> $GITHUB_OUTPUT
            echo 'EOF' >> $GITHUB_OUTPUT
      - name: Create nightly release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          tag_name: nightly
          name: Z64Utils nightly ${{ steps.release_info.outputs.now }}
          body: |
            Nightly build of Z64Utils
            ${{ steps.release_info.outputs.message }}
          files: |
            ${{ steps.release_info.outputs.files }}
