name: PR

on: [pull_request]

jobs:
  check-format:
    uses: ./.github/workflows/format.yml
  build:
    uses: ./.github/workflows/build.yml
    with:
      version-suffix: ${{ github.sha }}
      archive-suffix: ${{ github.sha }}
